/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patisseriegestionnaire.ui.jpanel;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import patisseriegestionnaire.models.Gateau;

/**
 *
 * @author roman
 */
public class JPanelCaisse extends javax.swing.JPanel {

    private ArrayList<Gateau> listeGateau;
    
    private Color fondBt = Color.BLUE;
    private Font fontBt;
    
    
    private IPanelCaisse i;
    /**
     * Creates new form JPanelCaisse
     */
    public JPanelCaisse() {
        initComponents();
    }
    


    public JPanelCaisse(ArrayList<Gateau> listeGateau, Color fondBt, Font fontBt) {
        this.listeGateau = listeGateau;
        this.fondBt = fondBt;
        this.fontBt = fontBt;
        this.i = i;
        init(); 
    }
    
    
    
    public JPanelCaisse(ArrayList<Gateau> lGat){
        this.listeGateau = lGat;
        init();
        
    }

    public void setI(IPanelCaisse i) {
        this.i = i;
    }
    
   
    public void majListGateau(ArrayList<Gateau> listeGateau){
        if (this.listeGateau != listeGateau){
            this.listeGateau = listeGateau;
            this.removeAll();
            this.init();
        } 
    }
    

    private void init(){
        int nbcol = (this.listeGateau.size()<6)? 1:4;
        int nbligne = (this.listeGateau.size()/nbcol)+1;
        
        setMinimumSize(new java.awt.Dimension(331, nbligne*50));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(331, nbligne*50));
        
        super.setLayout(new java.awt.GridLayout(nbligne,nbcol,5,5));
        
        
        for (Gateau g : this.listeGateau){
            JButton jbutton = new JButton();
            jbutton.setText(g.getNom());
            jbutton.setFont(fontBt);
            jbutton.setBackground(fondBt);
            jbutton.setForeground(Color.white);
            jbutton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (i!=null) i.addGateau(g);
                }
            });
            add(jbutton);
        }
        
        
    }

    @Override
    public String toString() {
        return "JPanelCaisse{" + this.listeGateau.size();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(331, 700));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(331, 700));
        setLayout(new java.awt.GridLayout(2, 4, 5, 5));

        jButton1.setText("jButton1");
        add(jButton1);

        jButton2.setText("jButton2");
        add(jButton2);

        jButton3.setText("jButton3");
        add(jButton3);

        jButton4.setText("jButton4");
        add(jButton4);

        jButton5.setText("jButton1");
        add(jButton5);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * Listener permettant de capter les action du JPanelCaisse
     * 
     */
    public interface IPanelCaisse {

        public void addGateau(patisseriegestionnaire.models.Gateau g);
    
    }
}

